name: visual tests

on:
  pull_request:

env:
  NODE_VERSION: 10
  DB_NAME: cdhweb
  DB_USER: cdhweb
  DB_PASSWORD: cdhweb
  DJANGO_DB_BACKEND: postgresql

jobs:
  visual-tests:
    name: Visual regression tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ hashFiles('package-lock.json') }}
            npm-

      - name: Install JS dependencies
        run: npm ci

      - name: Get Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            pip-${{ hashFiles('requirements/*.txt') }}
            pip-

      - name: Install dependencies
        run: pip install -r requirements/test.txt

      - name: Setup local_settings.py
        run: |
          cp ci/testsettings.py cdhweb/local_settings.py
          python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> cdhweb/local_settings.py

      - name: Migrate database
        run: python manage.py migrate

      - name: Build static assets
        run: python manage.py compress

      - name: Take DOM snapshots and upload to Percy
        run: npm test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
